# Generated by Django 3.2.6 on 2021-10-21 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursenest_app', '0002_auto_20211021_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
